### ISSUE TITLE
release plan

### ISSUE THREAD

**Issue by hannesm** [hannesm/jackline#25]
before 0.1 I'd like to finish the following tasks:
- [x] #2 otr more dynamic policy and per-user
- [x] #17 heartbeat
- [x] XEP-0184 (Message Delivery Receipts)
- [x] fix subtle OTR/DSA bug (which I can reproduce and only need some brain hours)
- [x] #7 proper escaping of xml entities (both directions)
- [x] multiple session for individual contact (touches #51 #20)
- [x] notifications #38 #55 #56
- [x] multi-user chat #20

**Comment by hannesm** [comment]
updated with tonights current goals..

**Comment by hannesm** [comment]
complications arise since I depend on a heavily patched `erm_xmpp` which I am not the maintainer of (and other dependent projects might break with my changes) -- unclear how to handle this in opam for a release -- maybe fork erm_xmpp to another opam package erm_xmpp_fork? any advise from someone?

**Comment by dbuenzli** [comment]
Write a good `xmpp` library using a decent xml library ?

**Comment by cfcs** [comment]
#12 would be nice to have, too, so users don't have to install another client to do that first :)

**Comment by hannesm** [comment]
I'll just close this useless issue... there are other issues open and I don't see a reason for a release (happy to have users who use git master all the time ;)
